services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: ${NAME}
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/deploy/subbox/users/${SUBBOXUSERNAME}/beets/config:/config
      - type: volume
        source: private-music
        target: /music
        volume:
          nocopy: true
          subpath: ${SUBBOXUSERNAME}
      - type: volume
        source: private-staged
        target: /downloads
        volume:
          nocopy: true
          subpath: ${SUBBOXUSERNAME}
    ports:
      - ${SUBBOXPORT}:8337
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik

volumes:
  private-staged:
    external: true
    name: private-staged
  private-music:
    external: true
    name: private-music
