---
services:
  beets:
    privileged: false
    image: lscr.io/linuxserver/beets:latest
    container_name: ${NAME}
    user: "501:20"
    environment:
      - PUID=501
      - PGID=20
      - TZ=Etc/UTC
    volumes:
      - /Users/lukepurnell/workspace/subbox/users/${SUBBOXUSERNAME}/beets/config:/config
      - type: volume
        source: private-music
        target: /music
        volume:
          nocopy: true
          subpath: ${SUBBOXUSERNAME}
      - type: volume
        source: private-staged
        target: /downloads
        volume:
          nocopy: true
          subpath: ${SUBBOXUSERNAME}
    ports:
      - ${SUBBOXPORT}:8337
    restart: unless-stopped
    networks:
      #- traefik_default
      - proxy
networks:
  #traefik_default:
  #  external: true
  #  name: traefik_default
  proxy:
    external: true

volumes:
  private-staged:
    external: true
    name: private-staged
  private-music:
    external: true
    name: private-music
