---
version: "2.1"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: ${NAME}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/lajp/subbox/${SUBBOXUSERNAME}/beets/config:/config
      - /Users/lajp/subbox/${SUBBOXUSERNAME}/nav_music:/music
      - /Users/lajp/subbox/${SUBBOXUSERNAME}/beets/download:/downloads
    ports:
      - ${SUBBOXPORT}:8337
    restart: unless-stopped
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
    name: traefik_default
