version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: root
    ports:
      - 8081:8080
    volumes:
      - user-updownloads:/data/users:z
      - /Users/lajp/subbox/docker-compose/filebrowser/config:/config
    #environment:
      #- FB_BASEURL=/filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  user-updownloads:
    driver: local
    name: user-updownloads
