version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: root
    ports:
      - 8081:8080
    volumes:
      - public-uploads:/data/public/uploads
      - private-updownloads:/data/private/users:z
      - /Users/lukepurnell/workspace/subbox/docker-compose/filebrowser/config:/config
    #environment:
      #- FB_BASEURL=/filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

volumes:
  private-updownloads:
    driver: local
    name: private-updownloads
  public-uploads:
    driver: local
    name: public-uploads
