services:
  navidrome:
    privileged: false
    image: deluan/navidrome:0.60.3
    restart: unless-stopped
    container_name: "${NAME}"
    user: "501:20"
    #group_add:
    #  - "20"
    ports:
      - "${SUBBOXPORT}:4533"
    environment:
      ND_SCANSCHEDULE: 0
      ND_LOGLEVEL: debug
      ND_SESSIONTIMEOUT: 24h
      ND_ENABLEINSIGHTSCOLLECTOR: false
      ND_SUBSONIC_DEFAULTREPORTREALPATH: true
      ND_COVERARTPRIORITY: "embedded"
      ND_MUSICFOLDER: "/music/${SUBBOXUSERNAME}"
      ND_DATAFOLDER: "/users/${SUBBOXUSERNAME}/data"
      # must add this so navidrome can respond to the path navidrome is to be accessed on via traefik
    volumes:
      - "/Users/lukepurnell/workspace/subbox/users:/users"
      - "private-music:/music:ro"
    networks:
      #- traefik_default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.docker.localhost`)"
      - "traefik.http.services.${NAME}.loadbalancer.server.port=4533"
      - "traefik.http.routers.${NAME}.tls=true"
      - "traefik.http.routers.${NAME}.middlewares=navcors"
      - "traefik.http.middlewares.navcors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.navcors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.navcors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.navcors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.navcors.headers.addvaryheader=true"

volumes:
  #public-music:
  #  external: true
  private-music:
    external: true
    name: private-music


networks:
  proxy:
    external: true
  #traefik_default:
  #  external: true
  #  name: traefik_default
