services:
  navidrome:
    image: deluan/navidrome:latest
    #image: laker93/neodrome:v1.2.11
    restart: unless-stopped
    container_name: "${NAME}"
    user: "501:20"
    ports:
      - "${SUBBOXPORT}:4533"
    environment:
      ND_SCANSCHEDULE: 0
      ND_LOGLEVEL: debug
      ND_SESSIONTIMEOUT: 24h
      # must add this so navidrome can respond to the path navidrome is to be accessed on via traefik
      ND_BASEURL: /${NAME}
      # improve performance by using the same artwork for each track in an album
      ND_ENABLEINSIGHTCOLLECTOR: false
      ND_SUBSONIC_DEFAULTREPORTREALPATH: true
      ND_ENABLEMEDIAFILECOVERART: false
      ND_COVERARTPRIORITY: "embedded"
      ND_BACKUP_PATH: /backup/navidrome/${SUBBOXUSERNAME}
      ND_BACKUP_SCHEDULE: 0 * * * *
      ND_BACKUP_COUNT: 3
    volumes:
      - "/Users/lajp/subbox/private/${SUBBOXUSERNAME}/navidrome/data:/data"
      - type: volume
        source: private-music
        target: /music/private
        read_only: false
        volume:
          nocopy: true
          subpath: ${SUBBOXUSERNAME}
      - type: volume
        source: private-music
        target: /backup
        read_only: false
        volume:
          nocopy: true
          subpath: backup/${SUBBOXUSERNAME}
      #- "public-music:/music/public:ro"
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`sub-box.net`) || PathPrefix(`/${NAME}`)"

      - "traefik.http.services.${NAME}.loadbalancer.server.port=4533"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=le"
      - "traefik.http.routers.${NAME}.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

volumes:
  #public-music:
  #  external: true
  private-music:
    external: true
    name: private-music


networks:
  traefik_default:
    external: true
    name: traefik_default
