version: '3.4'
services:
  navidrome:
    image: laker93/neodrome:latest
    restart: unless-stopped
    container_name: "${NAME}"
    user: "501:20"
    ports:
      - "${SUBBOXPORT}:4533"
    environment:
      #ND_SCANSCHEDULE: 1
      ND_LOGLEVEL: debug
      ND_SESSIONTIMEOUT: 24h
      # must add this so navidrome can respond to the path navidrome is to be accessed on via traefik
      #ND_BASEURL: /navidrome
    volumes:
      - "/Users/lajp/subbox/${SUBBOXUSERNAME}/navidrome/data:/data"
      - "/Users/lajp/subbox/${SUBBOXUSERNAME}/nav_music:/music:ro"
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
    name: traefik_default
