version: '3.4'
services:
  navidromelajp:
    image: laker93/neodrome:latest
    restart: unless-stopped
    container_name: "${NAME}"
    user: "501:20"
    ports:
      - "${SUBBOXPORT}:4533"
    environment:
      #ND_SCANSCHEDULE: 1
      ND_LOGLEVEL: debug
      ND_SESSIONTIMEOUT: 24h
      # must add this so navidrome can respond to the path navidrome is to be accessed on via traefik
      #ND_BASEURL: /navidrome
      ND_CONFIGFILE: /data/navidrome.toml
    volumes:
      - "/Users/lukepurnell/workspace/subbox/private/${SUBBOXUSERNAME}/navidrome/data:/data"
      - "/Users/lukepurnell/workspace/subbox/private/${SUBBOXUSERNAME}/navidrome/data/navidrome.toml:/data/navidrome.toml"
      - type: volume
        source: private-music
        target: /music
        read_only: true
        volume:
          nocopy: true
          subpath: ${SUBBOXUSERNAME}
    networks:
      - traefik_default

volumes:
  private-music:
    external: true
    name: private-music


networks:
  traefik_default:
    external: true
    name: traefik_default
