version: '3.4'
services:
  navidrome:
    image: laker93/neodrome:latest
    restart: unless-stopped
    container_name: "${NAME}"
    user: "501:20"
    ports:
      - "${SUBBOXPORT}:4533"
    environment:
      #ND_SCANSCHEDULE: 1
      ND_LOGLEVEL: debug
      ND_SESSIONTIMEOUT: 24h
      # must add this so navidrome can respond to the path navidrome is to be accessed on via traefik
      ND_BASEURL: /${NAME}
    volumes:
      - "/Users/lukepurnell/subbox/${SUBBOXUSERNAME}/navidrome/data:/data"
      - "/Users/lukepurnell/subbox/${SUBBOXUSERNAME}/nav_music:/music:ro"
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`sub-box.net`) || PathPrefix(`/${NAME}`)"

      - "traefik.http.services.${NAME}.loadbalancer.server.port=4533"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=le"
networks:
  traefik_default:
    external: true
    name: traefik_default
